# Inspired by https://github.com/golangci/golangci-lint/blob/54bfbb9a52299b6ecbdde9365282aa40a5561bf1/.golangci.yml#L1
linters-settings:
  linters:
    disable-all: true
    enable:
      - bodyclose
      - deadcode
      - depguard
      - dogsled
      - dupl
      - errcheck
      - exportloopref
      - exhaustive
      - funlen
      - gochecknoinits
      - goconst
      - gocritic
      - gocyclo
      - gofmt
      - goimports
      - golint
      - gomnd
      - goprintffuncname
      - gosec
      - gosimple
      - govet
      - ineffassign
      - lll
      - misspell
      - nakedret
      - noctx
      - nolintlint
      - rowserrcheck
      - staticcheck
      - structcheck
      - stylecheck
      - typecheck
      - unconvert
      - unparam
      - unused
      - varcheck
      - whitespace

  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
