name: Installation Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  install_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      PCT_INSTALL_DEBUG: true
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Latest Tag (Windows)
      id: latest_tag
      if: runner.os == 'Windows'
      run: |
        $TagVersion = git tag --list |
          Where-Object { $_ -match '^\d+\.\d+\.\d+$' } |
          Sort-Object -Descending |
          Select-Object -First 1
        echo "::set-output name=tag::0.4.0 d18bd02"
    - name: Install PCT (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        . .\tools\install.ps1; Install-Pct
    - name: Validate install (Windows)
      if: runner.os == 'Windows'
      run: |
        $HomeDir = Get-Item ~ | Select-Object -ExpandProperty FullName
        $PctPath = "${HomeDir}\.puppetlabs\pct\pct.exe"
        $verInfo = & $PctPath --version |
          Select-Object -First 1 |
          ForEach-Object { $_ -split " " } |
          Select-Object -Skip 1 -First 2
        if (& $PctPath --version | Out-String -Stream | Select-String -Pattern '${{ steps.latest_tag.outputs.tag }}') {
          exit 0
        } else {
          exit 1
        }
    - name: Install PCT (Unix)
      if: runner.os != 'Windows'
      run: ./tools/install.sh
    - name: Validate install (Unix)
      if: runner.os != 'Windows'
      run: $HOME/.puppetlabs/pct/pct --version | grep "pct $(git tag | tail -n 1)"
